Repository woowacourse-teams/2020-14f-guys, pull requests merged in 2020-08, with the labels that each got.

#144 fix: GitHub actions ci
  .github/workflows/gradle.yml
Labels: git, 인프라

#146 chore: gradle.yml 토큰 오타 수정
  .github/workflows/gradle.yml
Labels: git

#158 refactor: 코드 컨벤션 점검 및 todo 추가
  src/main/java/com/woowacourse/pelotonbackend/Application.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/CertificationController.java
  src/main/java/com/woowacourse/pelotonbackend/common/ErrorCode.java
  src/main/java/com/woowacourse/pelotonbackend/common/ErrorResponse.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/DuplicateException.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/InvalidInputException.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/MemberIdInvalidException.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/MemberNotFoundException.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/NotFoundException.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/RaceNotFoundException.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/ReportDuplicateException.java
  src/main/java/com/woowacourse/pelotonbackend/member/application/LoginService.java
  src/main/java/com/woowacourse/pelotonbackend/member/domain/Member.java
  src/main/java/com/woowacourse/pelotonbackend/member/infra/KakaoAPIService.java
  src/main/java/com/woowacourse/pelotonbackend/member/infra/dto/KakaoTokenResponse.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/LoginMemberArgumentResolver.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/MemberController.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberResponse.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberResponses.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/Mission.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/TimeDuration.java
  src/main/java/com/woowacourse/pelotonbackend/race/application/RaceService.java
  src/main/java/com/woowacourse/pelotonbackend/race/domain/DateDuration.java
  src/main/java/com/woowacourse/pelotonbackend/race/domain/RaceCategory.java
  src/main/java/com/woowacourse/pelotonbackend/race/exception/RaceNotFoundException.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/RaceController.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceUpdateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/report/application/ReportService.java
  src/main/java/com/woowacourse/pelotonbackend/report/domain/ReportRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/report/presentation/ReportController.java
  src/main/java/com/woowacourse/pelotonbackend/report/presentation/ReportCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/rider/application/RiderService.java
  src/main/java/com/woowacourse/pelotonbackend/rider/domain/Rider.java
  src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepository.java
  src/main/java/com/woowacourse/pelotonbackend/rider/presentation/RiderController.java
  src/main/java/com/woowacourse/pelotonbackend/rider/presentation/RiderResponse.java
  src/main/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/support/AuthorizationExtractor.java
  src/main/java/com/woowacourse/pelotonbackend/support/BearerAuthInterceptor.java
  src/main/java/com/woowacourse/pelotonbackend/support/JwtTokenProvider.java
  src/main/java/com/woowacourse/pelotonbackend/support/RandomGeneratorImpl.java
  src/main/java/com/woowacourse/pelotonbackend/vo/Cash.java
  src/test/java/com/woowacourse/pelotonbackend/member/application/LoginServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/MemberControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/RaceAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/application/RaceServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/RaceControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/RaceUpdateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/report/domain/ReportFixture.java
  src/test/java/com/woowacourse/pelotonbackend/report/presentation/ReportControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/RiderControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/support/JwtTokenProviderTest.java
Labels: 컨벤션

#162 refactor: member id, certification id 쌍이 이미 존재할 때, 예외처리 구현
  src/main/java/com/woowacourse/pelotonbackend/report/domain/ReportRepositoryCustomImpl.java
  src/test/java/com/woowacourse/pelotonbackend/report/domain/ReportRepositoryTest.java
Labels: spring data jdbc

#143 refactor: 프로필 사진이 null일 경우 db 저장 허용 및 ConstraintViolationException 예외처리 로직 구현
  src/main/java/com/woowacourse/pelotonbackend/common/GlobalExceptionHandler.java
  src/main/java/com/woowacourse/pelotonbackend/member/domain/Member.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/MemberControllerTest.java
Labels: 백엔드

#170 chore: github actions ci 제거
  .github/workflows/gradle.yml
Labels: wontfix

#172 인덱스 페이지 구현
  src/main/resources/static/index.html
Labels: 인프라

#171 레이스 생성화면 UI 수정
  peloton-frontend/component/home/HomeNavigationRoot.js
  peloton-frontend/component/home/racecreate/CalendarButton.js
  peloton-frontend/component/home/racecreate/InputBox.js
  peloton-frontend/component/home/racecreate/InputRaceDates.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/component/home/racecreate/InputRaceInfo.js
  peloton-frontend/component/home/racecreate/RaceCreateUnit.js
  peloton-frontend/component/home/racecreate/RaceCreateView.js
  peloton-frontend/component/login/KakaoLoginWebView.js
  peloton-frontend/component/login/SubmitButton.js
  peloton-frontend/component/login/WebViewCloseButton.js
  peloton-frontend/component/profile/profileedit/ProfileEditInfo.js
  peloton-frontend/package.json
  peloton-frontend/state/race/CreateState.js
  peloton-frontend/utils/util.js
  peloton-frontend/yarn.lock
Labels: 프론트엔드

#179 feat: Rider CRUD 기능 구현
  peloton-frontend/component/profile/profileedit/ProfileEditInfo.js
  src/main/java/com/woowacourse/pelotonbackend/member/application/LoginService.java
  src/main/java/com/woowacourse/pelotonbackend/member/domain/Member.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/MemberController.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceUpdateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/rider/application/RiderService.java
  src/main/java/com/woowacourse/pelotonbackend/rider/domain/Rider.java
  src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderCustomRepository.java
  src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepositoryImpl.java
  src/main/java/com/woowacourse/pelotonbackend/rider/presentation/RiderController.java
  src/main/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderResponse.java
  src/main/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderResponses.java
  src/main/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderUpdateRequest.java
  src/test/java/com/woowacourse/pelotonbackend/member/domain/LoginFixture.java
  src/test/java/com/woowacourse/pelotonbackend/rider/acceptance/RiderAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/application/RiderServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderFixture.java
  src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/RiderControllerTest.java
Labels: 백엔드

#178 feat: race 상세 정보 페이지 UI 수정
  peloton-frontend/component/ApplicationNavigationRoot.js
  peloton-frontend/component/home/HomeNavigationRoot.js
  peloton-frontend/component/home/homemain/Home.js
  peloton-frontend/component/home/homemain/HomeBanner.js
  peloton-frontend/component/home/homemain/RaceItem.js
  peloton-frontend/component/home/race/RaceCertificationImage.js
  peloton-frontend/component/home/race/RaceDetail.js
  peloton-frontend/component/home/race/RaceDetailInfo.js
  peloton-frontend/component/home/race/RaceSpec.js
  peloton-frontend/component/home/race/RaceSpecItem.js
  peloton-frontend/component/home/race/RaceSubTitle.js
  peloton-frontend/component/home/race/ShareButton.js
  peloton-frontend/component/home/racecreate/CalendarButton.js
  peloton-frontend/component/home/racecreate/CategorySelection.js
  peloton-frontend/component/home/racecreate/InputBox.js
  peloton-frontend/component/login/ChangeProfile.js
  peloton-frontend/component/login/KakaoLoginWebView.js
  peloton-frontend/component/login/Login.js
  peloton-frontend/component/login/LoginTitle.js
  peloton-frontend/component/login/NicknameInput.js
  peloton-frontend/component/login/ProfileImage.js
  peloton-frontend/component/login/SubmitButton.js
  peloton-frontend/component/profile/CustomButton.js
  peloton-frontend/component/profile/cashupdate/CashUpdate.js
  peloton-frontend/component/profile/profiledetail/MemberInfoDetail.js
  peloton-frontend/component/profile/profiledetail/ProfileDetail.js
  peloton-frontend/component/profile/profileedit/ProfileEdit.js
  peloton-frontend/component/profile/profileedit/ProfileEditInfo.js
  peloton-frontend/component/profile/profileedit/ProfileImageEdit.js
  peloton-frontend/component/profile/profileedit/SignOutButtonContainer.js
  peloton-frontend/component/profile/profileedit/UnregisterButtonContainer.js
  peloton-frontend/utils/LoadingIndicator.js
  peloton-frontend/utils/ReadMore.js
  peloton-frontend/utils/constants.js
  peloton-frontend/yarn.lock
Labels: 프론트엔드

#203 fix: 카카오톡 프사가 없으면 로그인할 수 없던 버그 수정
  src/main/resources/db/changelog-master.xml
  src/main/resources/db/changes/changelog-schema-1.0.0.xml
  src/main/resources/db/changes/changelog-schema-1.0.1.xml
  src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberRepositoryTest.java
Labels: bug, 백엔드

#205 fix: Spring boot Profile을 읽어올 수 없던 버그 수정
  src/main/resources/application.yml
  src/main/resources/db/changes/changelog-schema-1.0.1.xml
Labels: bug, 백엔드

#208 fix: Mariadb에서 encoding 문제로 한글이 저장되지 않던 버그 수정
  src/main/resources/db/changelog-master.xml
  src/main/resources/db/changes/changelog-schema-1.0.2.xml
Labels: bug, 백엔드

#200 feat: Race 생성할 때, 미션도 같이 생성하는 기능 구현
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/TimeDuration.java
  src/main/java/com/woowacourse/pelotonbackend/mission/application/MissionService.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/DateTimeDuration.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/Mission.java
  src/main/java/com/woowacourse/pelotonbackend/race/application/RaceService.java
  src/main/java/com/woowacourse/pelotonbackend/race/domain/RaceCategory.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/support/CustomDateParser.java
  src/test/java/com/woowacourse/pelotonbackend/docs/DocumentFormatGenerator.java
  src/test/java/com/woowacourse/pelotonbackend/docs/RaceDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/mission/application/MissionServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionFixture.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/application/RaceServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/domain/RaceFixture.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/RaceControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceCreateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/support/CustomDateParserTest.java
Labels: 백엔드

#201 refactor: ArgumentResolver 예외 처리 및 테스트 구현
  src/main/java/com/woowacourse/pelotonbackend/member/application/MemberService.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/LoginMemberArgumentResolver.java
  src/test/java/com/woowacourse/pelotonbackend/infra/login/LoginMemberArgumentResolverTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/LoginMemberArgumentResolverIntegrationTest.java
Labels: 백엔드

#212 fix: Profile Image 관련 bug fix
  peloton-frontend/component/certification/Certification.js
  peloton-frontend/component/login/ProfileImage.js
  peloton-frontend/component/login/ProfileImageSelect.js
  peloton-frontend/component/profile/ProfileDefaultImage.js
  peloton-frontend/component/profile/ProfileImageEditButton.js
  peloton-frontend/component/profile/profiledetail/MemberInfo.js
  peloton-frontend/component/profile/profiledetail/ProfileDetail.js
  peloton-frontend/component/profile/profileedit/ProfileImageEdit.js
  peloton-frontend/utils/api/MemberApi.js
  peloton-frontend/utils/constants.js
  src/main/java/com/woowacourse/pelotonbackend/infra/login/dto/KakaoUserResponse.java
  src/main/java/com/woowacourse/pelotonbackend/support/jsonparser/KakaoUserResponseDeserializer.java
Labels: bug

#211 feat: Member id로 참여중인 race들을 모두 조회하는 기능
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/woowacourse/pelotonbackend/config/WebMvcConfig.java
  src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/QueryController.java
  src/main/java/com/woowacourse/pelotonbackend/race/application/RaceService.java
  src/main/java/com/woowacourse/pelotonbackend/race/domain/RaceRepository.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/RaceController.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceResponse.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceResponses.java
  src/main/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderResponses.java
  src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/infra/login/LoginMemberArgumentResolverTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/application/MemberServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberFixture.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/MemberControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberResponsesTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/presentation/QueryControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/RaceAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/application/RaceServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/domain/RaceFixture.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/RaceControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderFixture.java
Labels: 백엔드

#224 fix: race responses에 jsonNamingStrategy 추가
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceResponses.java
  src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java
Labels: 백엔드

#222 fix: S3 경로 문제 해결
  src/main/java/com/woowacourse/pelotonbackend/certification/application/CertificationService.java
  src/main/java/com/woowacourse/pelotonbackend/infra/upload/S3UploadService.java
  src/main/java/com/woowacourse/pelotonbackend/member/application/MemberService.java
  src/main/java/com/woowacourse/pelotonbackend/support/RandomGenerator.java
  src/main/java/com/woowacourse/pelotonbackend/support/RandomGeneratorImpl.java
  src/test/java/com/woowacourse/pelotonbackend/infra/upload/UploadFixture.java
  src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberFixture.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberProfileResponseTest.java
Labels: bug, 백엔드, 인프라

#225 feat: API 문서를 index 페이지에 추가
  src/main/resources/static/index.html
Labels: documentation

#207 Certification CRUD 구현 완료 했습니다.
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/woowacourse/pelotonbackend/certification/application/CertificationService.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/Certification.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepository.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSql.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/CertificationController.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationDescriptionUpdateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationResponse.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationResponses.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationStatusUpdateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/common/ErrorCode.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/CertificationNotFoundException.java
  src/main/java/com/woowacourse/pelotonbackend/member/application/MemberService.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/LoginMemberArgumentResolver.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberResponse.java
  src/main/java/com/woowacourse/pelotonbackend/mission/application/MissionService.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/Mission.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/query/RaceCertificationsResponse.java
  src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/QueryController.java
  src/main/java/com/woowacourse/pelotonbackend/vo/ImageUrl.java
  src/test/java/com/woowacourse/pelotonbackend/certification/acceptance/CertificationAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/application/CertificationServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationFixture.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSqlTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/CertificationControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationCreateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationDescriptionUpdateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationStatusUpdateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/docs/CertificationDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/docs/DocumentFormatGenerator.java
  src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/mission/application/MissionServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionFixture.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/presentation/QueryControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/RiderControllerTest.java
Labels: 백엔드

#220 feat: 레이스 참여 링크 기능 구현했습니다.
  peloton-frontend/App.js
  peloton-frontend/app.json
  peloton-frontend/assets/default-image-background.png
  peloton-frontend/assets/icn_back_dark.png
  peloton-frontend/component/certification/Certification.js
  peloton-frontend/component/home/HomeNavigationRoot.js
  peloton-frontend/component/home/homemain/Home.js
  peloton-frontend/component/home/homemain/HomeBanner.js
  peloton-frontend/component/home/race/GoBackButton.js
  peloton-frontend/component/home/race/LinkCopyButton.js
  peloton-frontend/component/home/race/RaceCertificationImage.js
  peloton-frontend/component/home/race/RaceDeepLinkPage.js
  peloton-frontend/component/home/race/RaceDetail.js
  peloton-frontend/component/home/race/RaceShareButton.js
  peloton-frontend/component/home/race/RaceSpec.js
  peloton-frontend/component/home/racecreate/CategorySelection.js
  peloton-frontend/component/home/racecreate/InputRaceDates.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/component/home/racecreate/InputRaceInfo.js
  peloton-frontend/component/home/racecreate/RaceCreateUnit.js
  peloton-frontend/component/login/ChangeProfile.js
  peloton-frontend/component/login/KakaoLoginWebView.js
  peloton-frontend/component/login/Login.js
  peloton-frontend/component/login/ProfileImage.js
  peloton-frontend/component/login/ProfileImageSelect.js
  peloton-frontend/component/login/SubmitButton.js
  peloton-frontend/component/profile/ProfileEditButton.js
  peloton-frontend/component/profile/ProfileImage.js
  peloton-frontend/component/profile/ProfileImageEditButton.js
  peloton-frontend/component/profile/ProfileStackRoot.js
  peloton-frontend/component/profile/profiledetail/MemberInfo.js
  peloton-frontend/component/profile/profiledetail/ProfileDetail.js
  peloton-frontend/component/profile/profileedit/CashUpdate.js
  peloton-frontend/component/profile/profileedit/NameUpdate.js
  peloton-frontend/component/profile/profileedit/ProfileEdit.js
  peloton-frontend/component/profile/profileedit/ProfileEditInfo.js
  peloton-frontend/component/profile/profileedit/ProfileImageEdit.js
  peloton-frontend/component/profile/profileedit/ProfileImageEditIcon.js
  peloton-frontend/component/profile/profileedit/ProfileInfoEdit.js
  peloton-frontend/component/profile/profileedit/UnregisterButtonContainer.js
  peloton-frontend/package-lock.json
  peloton-frontend/package.json
  peloton-frontend/state/member/MemberState.js
  peloton-frontend/state/race/CreateState.js
  peloton-frontend/state/race/RaceState.js
  peloton-frontend/utils/api/MemberApi.js
  peloton-frontend/utils/api/RaceApi.js
  peloton-frontend/utils/constants.js
  peloton-frontend/utils/util.js
  peloton-frontend/yarn.lock
Labels: 프론트엔드

#216 feat: Race를 생성할 때, 미션 요일과 시간을 받는 기능 구현
  peloton-frontend/component/home/HomeNavigationRoot.js
  peloton-frontend/component/home/racecreate/CalendarButton.js
  peloton-frontend/component/home/racecreate/InputBox.js
  peloton-frontend/component/home/racecreate/InputRaceDates.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/component/home/racecreate/InputRaceInfo.js
  peloton-frontend/component/home/racecreate/InputRaceMissionDays.js
  peloton-frontend/component/home/racecreate/InputRaceMissionTime.js
  peloton-frontend/component/home/racecreate/MissionDayButton.js
  peloton-frontend/component/home/racecreate/MissionDaysSelector.js
  peloton-frontend/component/home/racecreate/RaceCreateUnit.js
  peloton-frontend/component/login/ProfileImage.js
  peloton-frontend/component/profile/ProfileImageEditButton.js
  peloton-frontend/utils/constants.js
Labels: 프론트엔드

#227 feat: 레이스 참여 관련 추가 기능 구현
  peloton-frontend/assets/race_category_1.jpg
  peloton-frontend/assets/race_category_2.jpg
  peloton-frontend/assets/race_category_3.jpg
  peloton-frontend/component/home/race/LinkCopyButton.js
  peloton-frontend/component/home/race/RaceDeepLinkPage.js
  peloton-frontend/component/home/race/RaceDetail.js
  peloton-frontend/component/home/race/RaceSpec.js
  peloton-frontend/component/home/racecreate/CategoryItem.js
  peloton-frontend/component/home/racecreate/CategorySelection.js
  peloton-frontend/component/home/racecreate/InputRaceDates.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/state/rider/RiderState.js
  peloton-frontend/utils/api/QueryApi.js
  peloton-frontend/utils/api/RaceApi.js
  peloton-frontend/utils/api/RiderApi.js
  peloton-frontend/utils/constants.js
Labels: 프론트엔드

#231 fix: ChangeProfile에서 닉네임이 정상적으로 수정되지 않는 버그 해결
  peloton-frontend/component/login/ChangeProfile.js
Labels: bug

#232 fix: 회원 탈퇴 버튼을 클릭 후 발생하는 버그 해결
  peloton-frontend/component/profile/profileedit/UnregisterButtonContainer.js
Labels: bug, 프론트엔드

#234 feat: 레이스 참여 페이지 수정
  peloton-frontend/assets/default-race-join.png
  peloton-frontend/component/ApplicationNavigationRoot.js
  peloton-frontend/component/HomeNavigationRoot.js
  peloton-frontend/component/ProfileStackRoot.js
  peloton-frontend/component/home/race/PaymentButton.js
  peloton-frontend/component/home/race/RaceDeepLinkPage.js
  peloton-frontend/component/home/race/RaceJoinBody.js
  peloton-frontend/component/home/race/RaceJoinTitle.js
  peloton-frontend/component/home/race/RaceSpecItem.js
  peloton-frontend/component/profile/profileedit/ProfileInfoEdit.js
  peloton-frontend/utils/ReadMore.js
Labels: 프론트엔드

#237 feat: 중복된 엔티티 생성요청에 대한 방어로직 구현
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/woowacourse/pelotonbackend/certification/application/CertificationService.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSql.java
  src/main/java/com/woowacourse/pelotonbackend/common/ErrorCode.java
  src/main/java/com/woowacourse/pelotonbackend/common/GlobalExceptionHandler.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/CertificationDuplicatedException.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/RiderDuplicatedException.java
  src/main/java/com/woowacourse/pelotonbackend/rider/application/RiderService.java
  src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderCustomRepository.java
  src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepositoryImpl.java
  src/test/java/com/woowacourse/pelotonbackend/certification/acceptance/CertificationAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/application/CertificationServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/CertificationControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/docs/CertificationDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/docs/ReportDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/docs/RiderDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberFixture.java
  src/test/java/com/woowacourse/pelotonbackend/report/ReportAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/report/presentation/ReportControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/acceptance/RiderAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/application/RiderServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderFixture.java
  src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/RiderControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/support/AcceptanceTest.java
Labels: 백엔드

#244 fix: certification query 관련 수정
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSql.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/QueryController.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/presentation/QueryControllerTest.java
Labels: 백엔드

#235 feat: Member가 본인이 참여중인 레이스를 home화면에 볼 수 있는 기능
  peloton-frontend/component/home/homemain/RaceItem.js
  peloton-frontend/component/home/homemain/RaceItemImage.js
  peloton-frontend/component/home/homemain/RaceItemText.js
  peloton-frontend/component/home/homemain/RaceItems.js
  peloton-frontend/component/home/homemain/RaceList.js
  peloton-frontend/component/home/race/RaceDetail.js
  peloton-frontend/state/race/ResponseState.js
  peloton-frontend/utils/constants.js
  src/main/java/com/woowacourse/pelotonbackend/race/domain/RaceCategory.java
Labels: 백엔드, 프론트엔드

#245 refactor: 백엔드에서 UTC기준 ISO 8601형식을 사용하도록 수정
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/infra/upload/S3UploadService.java
  src/main/java/com/woowacourse/pelotonbackend/member/application/LoginService.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberCashUpdateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberProfileResponse.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/DateTimeDuration.java
  src/main/java/com/woowacourse/pelotonbackend/mission/presentation/dto/MissionCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/mission/presentation/dto/MissionUpdateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/race/domain/DateDuration.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderResponse.java
  src/main/java/com/woowacourse/pelotonbackend/support/RandomGeneratorImpl.java
  src/main/java/com/woowacourse/pelotonbackend/support/annotation/FutureOrPresentBasedUTC.java
  src/main/java/com/woowacourse/pelotonbackend/support/annotation/FutureOrPresentBasedUTCValidator.java
  src/main/java/com/woowacourse/pelotonbackend/support/jsonparser/ImageUrlDeserializer.java
  src/main/resources/db/changelog-master.xml
  src/main/resources/db/changes/changelog-schema-1.0.3.xml
  src/main/resources/db/changes/changelog-schema-1.0.4.xml
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationDescriptionUpdateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationStatusUpdateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/infra/login/dto/KakaoTokenResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/application/LoginServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/LoginMemberArgumentResolverIntegrationTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberCashUpdateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberCreateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberNameUpdateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberProfileResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionFixture.java
  src/test/java/com/woowacourse/pelotonbackend/mission/presentation/MissionControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/mission/presentation/dto/MissionCreateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/domain/RaceFixture.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceCreateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceDtoTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceRetrieveResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceUpdateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/report/presentation/dto/ReportCreateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderFixture.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderCreateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderResponsesTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderUpdateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/support/CustomDateParserTest.java
  src/test/java/com/woowacourse/pelotonbackend/support/annotation/FutureOrPresentBasedUTCValidatorTest.java
Labels: 백엔드

#238 캐시 계산 로직 백엔드로 이전하기 완료
  peloton-frontend/component/home/race/RaceDeepLinkPage.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/component/profile/profileedit/CashUpdate.js
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/woowacourse/pelotonbackend/common/ErrorCode.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/MoneyInvalidException.java
  src/main/java/com/woowacourse/pelotonbackend/member/application/MemberService.java
  src/main/java/com/woowacourse/pelotonbackend/member/domain/Member.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/MemberController.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberCashUpdateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/rider/application/RiderService.java
  src/main/java/com/woowacourse/pelotonbackend/vo/Cash.java
  src/test/java/com/woowacourse/pelotonbackend/docs/MemberDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/member/MemberAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/application/MemberServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberFixture.java
  src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/MemberControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberCreateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberResponsesTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/acceptance/RiderAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/application/RiderServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderFixture.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderCreateRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/presentation/dto/RiderResponsesTest.java
  src/test/java/com/woowacourse/pelotonbackend/support/AcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/vo/CashTest.java
Labels: 백엔드, 프론트엔드

#249 fix: 테스트코드 내 한글 제거
  src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberRepositoryTest.java
Labels: bug

#241 feat: 로그인된 멤버가 해야할 미션 목록을 가져오는 기능 구현
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/RaceNotFoundException.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/Mission.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/QueryController.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceCertificationsResponse.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/dto/UpcomingMissionResponse.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/dto/UpcomingMissionResponses.java
  src/main/resources/db/changes/changelog-schema-1.0.3.xml
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionFixture.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/presentation/QueryControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/domain/RaceFixture.java
  src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderFixture.java
Labels: 백엔드

#250 refactor: 레이스 카테고리 설명 추가 및 이미지 변경
  peloton-frontend/assets/race_category_1.jpg
  peloton-frontend/assets/race_category_2.jpg
  peloton-frontend/assets/race_category_3.jpg
  peloton-frontend/assets/race_category_books.jpg
  peloton-frontend/assets/race_category_exercise.jpg
  peloton-frontend/assets/race_category_leisure.jpg
  peloton-frontend/assets/race_category_meeting.jpg
  peloton-frontend/component/home/racecreate/CategorySelection.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/utils/constants.js
  src/main/java/com/woowacourse/pelotonbackend/race/domain/RaceCategory.java
Labels: 프론트엔드

#236 feat: 미션 인증 기능 구현
  peloton-frontend/App.js
  peloton-frontend/assets/default-race-thumbnail.jpg
  peloton-frontend/component/ApplicationNavigationRoot.js
  peloton-frontend/component/certification/Certification.js
  peloton-frontend/component/certification/CertificationItem.js
  peloton-frontend/component/certification/CertificationNavigationRoot.js
  peloton-frontend/component/certification/CertificationStateIcon.js
  peloton-frontend/component/certification/CertificationSubmit.js
  peloton-frontend/component/home/race/FullWidthButton.js
  peloton-frontend/component/home/race/LinkCopyButton.js
  peloton-frontend/component/home/race/PaymentButton.js
  peloton-frontend/component/home/race/RaceCertificationImage.js
  peloton-frontend/component/home/race/RaceCertificationImages.js
  peloton-frontend/component/home/race/RaceDeepLinkPage.js
  peloton-frontend/component/home/race/RaceDetail.js
  peloton-frontend/component/home/race/RaceShareButton.js
  peloton-frontend/component/home/racecreate/InputBox.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/component/profile/ProfileImage.js
  peloton-frontend/component/profile/ProfileImageEditButton.js
  peloton-frontend/component/profile/profileedit/CashUpdate.js
  peloton-frontend/component/profile/profileedit/SignOutButtonContainer.js
  peloton-frontend/state/certification/RaceMissionState.js
  peloton-frontend/state/race/RaceState.js
  peloton-frontend/utils/Permission.js
  peloton-frontend/utils/api/CertificationApi.js
  peloton-frontend/utils/api/RaceApi.js
  peloton-frontend/utils/constants.js
  peloton-frontend/utils/util.js
Labels: 프론트엔드

#251 refactor: 로그아웃, 삭제, 프로필이미지 업로드 수정했습니다.
  peloton-frontend/component/home/race/RaceShareButton.js
  peloton-frontend/component/login/ChangeProfile.js
  peloton-frontend/component/login/Login.js
  peloton-frontend/component/login/ProfileImageSelect.js
  peloton-frontend/component/profile/ProfileImage.js
  peloton-frontend/component/profile/ProfileImageEditButton.js
  peloton-frontend/component/profile/profiledetail/ProfileDetail.js
  peloton-frontend/component/profile/profileedit/ProfileImageEdit.js
  peloton-frontend/component/profile/profileedit/SignOutButtonContainer.js
  peloton-frontend/component/profile/profileedit/UnregisterButtonContainer.js
  peloton-frontend/state/member/MemberState.js
  peloton-frontend/utils/api/MemberApi.js
Labels: bug, 프론트엔드

#257 feat: Member를 id로 가져오는 기능 추가했습니다.
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSql.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/MemberController.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSqlTest.java
  src/test/java/com/woowacourse/pelotonbackend/docs/MemberDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/MemberControllerTest.java
Labels: 백엔드

#258 fix: Certification Response에 CreatedAt 필드 추가
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationResponse.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationFixture.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/CertificationControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationResponseTest.java
  src/test/java/com/woowacourse/pelotonbackend/docs/CertificationDocumentation.java
Labels: bug, 백엔드

#261 fix: certification fixture formatting
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationFixture.java
Labels: bug

#252 feat: 인증 생성 기능 구현
  peloton-frontend/component/certification/Certification.js
  peloton-frontend/component/certification/CertificationItem.js
  peloton-frontend/component/certification/CertificationSubmit.js
  peloton-frontend/utils/api/CertificationApi.js
  peloton-frontend/utils/api/QueryApi.js
  peloton-frontend/utils/constants.js
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/woowacourse/pelotonbackend/certification/application/CertificationService.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/Certification.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/CertificationController.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationDescriptionUpdateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationRequest.java
  src/main/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationStatusUpdateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/infra/upload/S3UploadService.java
  src/test/java/com/woowacourse/pelotonbackend/certification/CertificationAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/acceptance/CertificationAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/application/CertificationServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationFixture.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/CertificationControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/presentation/dto/CertificationRequestTest.java
  src/test/java/com/woowacourse/pelotonbackend/docs/CertificationDocumentation.java
  src/test/resources/SampleFileUpdated.jpeg
Labels: 백엔드, 프론트엔드

#256 feat: 레이스 상세정보 조회 기능 구현
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/QueryController.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceDetailResponse.java
  src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionFixture.java
  src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/presentation/QueryControllerTest.java
Labels: 백엔드

#266 fix: 인증 목록을 불러올 때, 남의 인증목록을 가져오던 버그 수정
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSql.java
  src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationFixture.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java
Labels: bug, 백엔드

#247 ErrorCode 클래스에서 Code를 변경했습니다.
  peloton-frontend/component/home/homemain/RaceList.js
  peloton-frontend/component/home/race/RaceDeepLinkPage.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/component/login/ChangeProfile.js
  peloton-frontend/component/login/Login.js
  peloton-frontend/component/profile/ProfileImageEditButton.js
  peloton-frontend/component/profile/profileedit/CashUpdate.js
  peloton-frontend/component/profile/profileedit/NameUpdate.js
  peloton-frontend/utils/api/MemberApi.js
  peloton-frontend/utils/api/RaceApi.js
  peloton-frontend/utils/api/RiderApi.js
  src/main/java/com/woowacourse/pelotonbackend/common/ErrorCode.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/LoginMemberArgumentResolverIntegrationTest.java
Labels: 컨벤션

#282 feat: race Id로 성취율을 계산하는 기능 구현
  src/docs/asciidoc/api-guide.adoc
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationSql.java
  src/main/java/com/woowacourse/pelotonbackend/common/ErrorCode.java
  src/main/java/com/woowacourse/pelotonbackend/common/exception/MissionCountInvalidException.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/dto/MemberResponse.java
  src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/QueryController.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceAchievementRate.java
  src/main/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceAchievementRates.java
  src/test/java/com/woowacourse/pelotonbackend/calculation/application/CalculationServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/calculation/domain/CalculationsTest.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationFixture.java
  src/test/java/com/woowacourse/pelotonbackend/docs/QueryDocumentation.java
  src/test/java/com/woowacourse/pelotonbackend/member/domain/MemberFixture.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionFixture.java
  src/test/java/com/woowacourse/pelotonbackend/query/application/QueryServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/presentation/QueryControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceAchievementRateTest.java
  src/test/java/com/woowacourse/pelotonbackend/query/presentation/dto/RaceAchievementRatesTest.java
  src/test/java/com/woowacourse/pelotonbackend/rider/domain/RiderFixture.java
Labels: 백엔드

#269 feat: license 고지
  peloton-frontend/component/ApplicationNavigationRoot.js
  peloton-frontend/component/ProfileStackRoot.js
  peloton-frontend/component/SettingNavigationRoot.js
  peloton-frontend/component/certification/Certification.js
  peloton-frontend/component/certification/CertificationDetail.js
  peloton-frontend/component/certification/CertificationSubmit.js
  peloton-frontend/component/home/homemain/Home.js
  peloton-frontend/component/home/homemain/RaceList.js
  peloton-frontend/component/home/race/LinkCopyButton.js
  peloton-frontend/component/home/race/RaceDeepLinkPage.js
  peloton-frontend/component/home/race/RaceDetail.js
  peloton-frontend/component/home/racecreate/InputRaceDates.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/component/home/racecreate/InputRaceInfo.js
  peloton-frontend/component/home/racecreate/InputRaceMissionDays.js
  peloton-frontend/component/home/racecreate/InputRaceMissionTime.js
  peloton-frontend/component/home/racecreate/RaceCreateUnit.js
  peloton-frontend/component/login/Login.js
  peloton-frontend/component/profile/ProfileImageEditButton.js
  peloton-frontend/component/profile/profiledetail/ProfileDetail.js
  peloton-frontend/component/profile/profileedit/CashUpdate.js
  peloton-frontend/component/profile/profileedit/NameUpdate.js
  peloton-frontend/component/setting/Announcement.js
  peloton-frontend/component/setting/AnnouncementItem.js
  peloton-frontend/component/setting/Setting.js
  peloton-frontend/component/setting/license/License.js
  peloton-frontend/component/setting/license/LicenseBody.js
  peloton-frontend/component/setting/license/LicenseTitle.js
  peloton-frontend/component/setting/license/RepositoryLicense.js
  peloton-frontend/component/setting/license/RepositoryName.js
  peloton-frontend/component/setting/license/RepositoryOwner.js
  peloton-frontend/component/setting/license/RepositoryUrl.js
Labels: 프론트엔드

#290 feat: cash-charge 방식 수정
  peloton-frontend/component/ProfileStackRoot.js
  peloton-frontend/component/profile/profiledetail/ProfileDetail.js
  peloton-frontend/component/profile/profileedit/CashUpdate.js
  peloton-frontend/component/profile/profileedit/ProfileEdit.js
  src/main/java/com/woowacourse/pelotonbackend/member/application/MemberService.java
  src/main/java/com/woowacourse/pelotonbackend/member/presentation/MemberController.java
  src/main/java/com/woowacourse/pelotonbackend/pendingcash/CashStatus.java
  src/main/java/com/woowacourse/pelotonbackend/pendingcash/PendingCash.java
  src/main/java/com/woowacourse/pelotonbackend/pendingcash/PendingCashRepository.java
  src/main/java/com/woowacourse/pelotonbackend/pendingcash/PendingCashService.java
  src/main/resources/db/changelog-master.xml
  src/main/resources/db/changes/changelog-schema-1.0.8.xml
  src/test/java/com/woowacourse/pelotonbackend/member/MemberAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/application/MemberServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/member/presentation/MemberControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/pendingcash/PendingCashServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/pendingcash/PendingFixture.java
Labels: 백엔드, 프론트엔드

#296 fix: 앱에서 카카오 로그인이 안되던 버그 수정
  peloton-frontend/utils/constants.js
Labels: bug, 프론트엔드

#297 fix: 테스트에서 날짜는 가변이지만 요일은 불변이어서 생기는 문제 해결
  src/test/java/com/woowacourse/pelotonbackend/race/domain/RaceFixture.java
Labels: bug, 백엔드

#301 fix: SQL IN 구문에 빈 리스트가 들어갈 경우 생기는 sql 오류 수정
  src/main/java/com/woowacourse/pelotonbackend/calculation/domain/CalculationRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/calculation/domain/CalculationRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/query/application/QueryService.java
  src/main/java/com/woowacourse/pelotonbackend/report/domain/ReportRepositoryCustom.java
  src/main/java/com/woowacourse/pelotonbackend/report/domain/ReportRepositoryCustomImpl.java
  src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderCustomRepository.java
  src/main/java/com/woowacourse/pelotonbackend/rider/domain/RiderRepositoryImpl.java
  src/test/java/com/woowacourse/pelotonbackend/certification/domain/CertificationRepositoryTest.java
  src/test/java/com/woowacourse/pelotonbackend/mission/domain/MissionRepositoryTest.java
Labels: bug, 백엔드

#299 feat: 정산 프론트 페이지 구현
  peloton-frontend/component/ApplicationNavigationRoot.js
  peloton-frontend/component/home/HomeNavigationRoot.js
  peloton-frontend/component/home/race/CalculationResult.js
  peloton-frontend/component/home/race/CalculationResults.js
  peloton-frontend/component/home/race/HalfWidthButton.js
  peloton-frontend/component/home/race/LinkCopyButton.js
  peloton-frontend/component/home/race/RaceCalculation.js
  peloton-frontend/component/home/race/RaceDetail.js
  peloton-frontend/state/certification/RaceAchievementState.js
  peloton-frontend/utils/api/CalculationApi.js
  peloton-frontend/utils/api/QueryApi.js
Labels: 프론트엔드

#310 fix: offset 버그 및 파일 경로 버그 픽스
  peloton-frontend/component/ApplicationNavigationRoot.js
  peloton-frontend/component/home/racecreate/InputRaceFee.js
  peloton-frontend/component/home/racecreate/RaceCreateUnit.js
Labels: bug, 프론트엔드

#313 feat: 회원 약관 동의 화면 구현
  peloton-frontend/component/home/HomeNavigationRoot.js
  peloton-frontend/component/home/race/GoBackButton.js
  peloton-frontend/component/login/Agreement.js
  peloton-frontend/component/login/Login.js
  peloton-frontend/component/login/LoginNavigationRoot.js
  peloton-frontend/component/profile/profiledetail/AchievementItem.js
  peloton-frontend/component/profile/profiledetail/ProfileDetail.js
  peloton-frontend/component/profile/profileedit/SignOutButtonContainer.js
  peloton-frontend/package.json
  peloton-frontend/utils/AgreementContent.js
  peloton-frontend/yarn.lock
Labels: 프론트엔드
