Repository woowacourse-teams/2020-14f-guys, pull requests merged in 2020-07, with the labels that each got.

#111 Race 삭제 기능 구현
  src/main/java/com/woowacourse/pelotonbackend/race/application/RaceService.java
  src/main/java/com/woowacourse/pelotonbackend/race/exception/RaceNotFoundException.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/RaceController.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/ErrorCode.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceRetrieveResponse.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceUpdateRequest.java
  src/test/java/com/woowacourse/pelotonbackend/race/RaceAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/application/RaceServiceTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/domain/RaceFixture.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/RaceControllerTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/RaceUpdateRequestTest.java
Labels: 백엔드

#116 Race 생성 기능 구현(프런트)
  peloton-frontend/App.js
  peloton-frontend/component/home/Home.js
  peloton-frontend/component/home/homemain/HomeMain.js
  peloton-frontend/component/home/homemain/HomeMainBanner.js
  peloton-frontend/component/home/homemain/RaceItem.js
  peloton-frontend/component/home/homemain/RaceItemImage.js
  peloton-frontend/component/home/homemain/RaceItemText.js
  peloton-frontend/component/home/homemain/RaceItems.js
  peloton-frontend/component/home/homemain/RaceList.js
  peloton-frontend/component/home/race/RaceDetail.js
  peloton-frontend/component/home/racecreate/CalendarButton.js
  peloton-frontend/component/home/racecreate/CategoryItem.js
  peloton-frontend/component/home/racecreate/CategorySelection.js
  peloton-frontend/component/home/racecreate/InputBox.js
  peloton-frontend/component/home/racecreate/InputRaceInfo.js
  peloton-frontend/component/home/racecreate/RaceCreateUnit.js
  peloton-frontend/component/home/racelist/RaceListTitle.js
  peloton-frontend/component/home/util/DateFormatter.js
  peloton-frontend/component/home/util/LoadingIndicator.js
  peloton-frontend/package.json
  peloton-frontend/state/loading/LoadingState.js
  peloton-frontend/state/race/CreateState.js
  peloton-frontend/utils/constants.js
  peloton-frontend/yarn.lock
  src/main/java/com/woowacourse/pelotonbackend/race/domain/DateDuration.java
  src/main/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceCreateRequest.java
  src/main/java/com/woowacourse/pelotonbackend/support/jsonparser/CashDeserializer.java
  src/main/java/com/woowacourse/pelotonbackend/support/jsonparser/CashSerializer.java
  src/main/java/com/woowacourse/pelotonbackend/support/jsonparser/LocalDateDeserializer.java
  src/main/java/com/woowacourse/pelotonbackend/support/jsonparser/LocalDateSerializer.java
  src/main/resources/application.properties
  src/test/java/com/woowacourse/pelotonbackend/race/RaceAcceptanceTest.java
  src/test/java/com/woowacourse/pelotonbackend/race/presentation/dto/RaceCreateRequestTest.java
Labels: 프론트엔드

#133 feat: Github actions CI
  .github/workflows/gradle.yml
Labels: git, 인프라
